version: '2'

services:
  wordpress:
    image: daihiguchi/wordpress:latest
    links:
      - db:mysql
    environment:
      WORDPRESS_DB_PASSWORD: mysql-password
    ports:
      - "9000:9000"

  db:
    image: daihiguchi/mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysql-password

  nginx:
    image: daihiguchi/nginx:latest
    volumes_from:
      - wordpress
    ports:
      - "80:80"
    links:
      - wordpress
